# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  name: 'Vladimir'

steps:

- task: NuGetCommand@2
  displayName: 'restore NuGet, nuget task'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'restore NuGet, DotNetCoreCLI task'
  inputs:
    command: 'restore'
    projects: '**/*/*.csproj'

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    arguments: '--configuration Debug'

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: 'test'

